
name: "Curl Docker Pihole"
description: "Curl"
version: "1.0.1"
slug: "dockerhole-curl"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
 80/tcp: 80
 53/tcp: 53
 53/udp: 53
 67/udp: 67
