name: "Pihole SH Installer"
description: "SH"
version: "1.0.3"
slug: "piholesh"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  80/tcp: 80
  53/tcp: 53
  53/udp: 53
  67/udp: 67
