version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "58:53/tcp"
      - "58:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: 'rodolfo'    
    volumes:
      - '/home/dietpi/.docker/pihole/etc-pihole/:/etc/pihole/'
      - '/home/dietpi/.docker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'    
    restart: unless-stopped
