name: "Command Docker Pihole Installer"
description: "Command Docker Pihole Installer"
version: "1.0.0"
slug: "dockerhole-compose"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
