---
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Wallabot z0r3f
version: "1.0.6"
slug: wallabot
description: Wallapop Bot
url: "https://github.com/koko004/hassio-repo/"
arch:
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  TELEGRAM_TOKEN: ""
image: "z0r3f/wallbot-docker:latest"
schema:
  TELEGRAM_TOKEN: str
