name: "Cloned Pihole installer"
description: "cloned"
version: "1.0.1"
slug: "clonedpihole"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  80/tcp: 80
  53/tcp: 53
  53/udp: 53
  67/udp: 67
