---
name: WallAlert Bot
version: 1.0.7
slug: wallalert-bot
description: Bot de Telegram para buscar artículos en Wallapop
url: https://github.com/koko004/wallalert-bot
codenotary: koko004@gmail.com
startup: services
init: false
arch:
  - aarch64
  - amd64
map:
  - share:rw
hassio_api: true
options:
  bot_token: ""
  profile: null
schema:
  bot_token: str
  profile: str?
